"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d h
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d i
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d j
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d k
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d l
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d m
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d n
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d o
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d p
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d q
"C:\Program Files\VeraCrypt\VeraCrypt.exe" /q /d r
